### ISSUE TITLE
ES256 implementation is incorrect

### ISSUE THREAD

**Issue by t089** [vapor/jwt-kit#100]
Hello, I found that JWTs signed with JWTKit `ES256` are not correctly validated by jwt.io. The reason is, that the signature is stored in the `DER` format instead of the format specified in the JWS [spec](https://tools.ietf.org/html/rfc7515#appendix-A.3).

For a possible fix, please take a look at the discussion at [kylebrowning/APNSwift#36](https://github.com/kylebrowning/APNSwift/issues/36) and [kylebrowning/APNSwift#37](https://github.com/kylebrowning/APNSwift/pull/37), [kylebrowning/APNSwift#38](https://github.com/kylebrowning/APNSwift/pull/38).

**Comment by tanner0101** [comment]
Thanks for reporting this. I've fixed the issue in https://github.com/vapor/jwt-kit/pull/102 and added a test against a token from JWT.io to ensure the serialization is correct.
