### ISSUE TITLE
Sporadic failure of ES256

### ISSUE THREAD

**Issue by t089** [vapor/jwt-kit#103]
The patch in #102 introduced a subtle bug: In case where the `r` or `s` value of the signature is a "small" number, `BN_bn2bin` will actually produce less than `32` bytes per value. In this case some `0` padding is necessary to make sure that the final signature is `2 x 32 = 64 bytes` long. See eg: [kylebrowning/APNSwift#48](https://github.com/kylebrowning/APNSwift/pull/48/files)

**Comment by t089** [comment]
To reproduce run 
`swift test --sanitize=address -c release -Xswiftc -enable-testing --disable-index-store`
in a loop until it fails.

**Comment by tanner0101** [comment]
@t089 thanks for the helpful report. I've added a test case for this and fixed the issue here: https://github.com/vapor/jwt-kit/pull/104
