### ISSUE TITLE
Can't create `GoogleIdentityToken` without a Decoder

### ISSUE THREAD

**Issue by laralove143** [vapor/jwt-kit#131]
**Is your feature request related to a problem? Please describe.**
Often times we provide properties of `GoogleIdentityToken` manually, as we get them through Google Docs etc, not from a JSON body. But because it extends `Decodable`, the automatic initializer isn't available, so the only way to create it (AFAIK) is to create a custom `Decodable` object, which is awkward and bad in performance. We can't even extend it with our own initializer because it contains `let` properties.

**Describe the solution you'd like**
An initializer could be added manually, if no less-boilerplate solution is found.

**Describe alternatives you've considered**
`GoogleIdentityTokenFactory` object (with the same properties as `GoogleIdentityToken`) that doesn't conform to `Decodable` (thus has the automatic memberwise initializer) and has a method that returns `GoogleIdentityToken` (or `GoogleIdentityToken` could have an initializer taking `GoogleIdentityTokenFactory`, for discoverability). I think this is overengineering it though, and doesn't provide less boilerplate.

**Additional context**
I may be missing something, because this looks like a very commonly used thing.

**Comment by 0xTim** [comment]
I see no reason why we can't add a public initialiser
