### ISSUE TITLE
JWTKit 5.0.0-RC.1 `.unverified` tokens can't be extracted without parser

### ISSUE THREAD

**Issue by Joannis** [vapor/jwt-kit#173]
### Describe the issue

Parser uses generics, but generics can't be iferred

### Vapor version

Hummingbird 2

### Operating system and version

macOS 15

### Swift version

Swift 6

### Steps to reproduce

<img width="467" alt="image" src="https://github.com/user-attachments/assets/e59677a2-890e-4cda-bdd5-b081fbdc4657">

**Comment by ptoffy** [comment]
That's a big oops, fix is in the works. Sorry! For now you should be able to do
```swift
try await keyCollection.unverified(token, as: Token.self, parser: DefaultJWTParser?.none)
```
Passing in a `DefaultJWTParser()` should work the same
