### ISSUE TITLE
Lower minimum iOS version

### ISSUE THREAD

**Issue by Joannis** [vapor/jwt-kit#180]
We'd love to use JWTKit for some of our iOS code, but we need to support iOS 15. Is it possible and feasible to lower the iOS requirement? A quick check doesn't seem to indicate any iOS 16+ dependencies.

**Comment by gwynne** [comment]
This is a bug, not a feature request. When the Swift 6 compatibility PR was merged, the OS versions in the 5.10 manifest were bumped, although they shouldn't have been IIUC.

**Comment by 0xTim** [comment]
We upped the minimum versions for JWTKit v5 so it's been like that for a while. I'm not against lowering it to iOS 15 but we probably need to have a discussion around our support rules and define them somewhere for new versions (e.g. should Vapor 5 support iOS 15 or should be go straight to 18 even if we're not using anything that requires it etc)

**Comment by Joannis** [comment]
I think iOS/macOS SDK considerations should use a completely different set of support rules compared to the likes of Swift toolchain versions. Bumping libraries to iOS 18+ unnecessarily simply prohibits use in almost every app.

**Comment by 0xTim** [comment]
Yeah it's a symptom of the platforms mess in SwiftPM. Very happy to accept a PR for iOS 15 though (and other related platforms) - I can't see that holding us up much in the future. Otherwise I'll get to it next week
