### ISSUE TITLE
v5 not building for iOS project

### ISSUE THREAD

**Issue by jdelaune** [vapor/jwt-kit#191]
### Describe the issue

Hitting compile issues when trying to build an iOS project with the v5 branch.

### Vapor version

5.0.0-rc.2

### Operating system and version

iOS 18.0

### Swift version

Swift Package Manager - Swift 6.0.0-dev

### Steps to reproduce

Getting various issues around `compressedRepresentation`. The iOS project I'm building is targeting iOS 16 and above.

```Protocol 'ECDSAPublicKey' requires 'compressedRepresentation' to be available in iOS 15.0 and newer```

### Outcome

It should build.

### Additional notes

Not sure if it's the same issue but it's also failing for build for iOS over at SPI https://swiftpackageindex.com/builds/C2B4497A-C8DE-40AD-A273-A504A3D3F31D

**Comment by ptoffy** [comment]
Could you check if https://github.com/vapor/jwt-kit/pull/192 solves your issue?

**Comment by ptoffy** [comment]
(I would have thought adding iOS CI would prevent something like this but oh well)

**Comment by jdelaune** [comment]
Yes that solves the issue for me. Thanks
