### ISSUE TITLE
Drop support for Swift 5

### ISSUE THREAD

**Issue by 0xTim** [vapor/jwt-kit#195]
JWTKit v5 should only support Swift 6

**Comment by adam-fowler** [comment]
Why?

**Comment by 0xTim** [comment]
It's causing issues trying to write some that produces no warnings/errors in both language versions. Higher up the list is we're going to move to Swift Testing which pretty much necessitates the need for Swift 6

**Comment by adam-fowler** [comment]
Last time I checked jwt-kit compiles in both 5.10 and 6.0 mode without issue.

**Comment by JaapWijnen** [comment]
Ah this is unfortunate. We're still stuck on an older swift toolchain and therefore can't use v5 of this package now anymore. We were hoping to get around issues we were having with v4.

**Comment by 0xTim** [comment]
This was mainly necessitated by the move to Swift Testing unfotunately
