### ISSUE TITLE
Encoding `ExpirationClaim` as `Int` stopped working

### ISSUE THREAD

**Issue by MahdiBM** [vapor/jwt-kit#206]
### Describe the issue

Encoding `ExpirationClaim` as `Int` stopped working 2 days ago in Penny.

### Vapor version

JWTKit v4, and also v5

### Operating system and version

Ubuntu jammy

### Swift version

I'm not certain, it might have started happening starting from Swift 6

### Steps to reproduce

This is what fixed the problem: https://github.com/vapor/penny-bot/commit/6000ed123d09813d095b4307290fa6257da83f0a.
Note that Penny does use the `integerSecondsSince1970`s `DateDecodingStrategy`s: [vapor/penny-bot/Lambdas/GHHooks/Authenticator.swift#L76](https://github.com/vapor/penny-bot/blob/6000ed123d09813d095b4307290fa6257da83f0a/Lambdas/GHHooks/Authenticator.swift#L76)

### Outcome

Penny throws these errors:

multipleErrors(["Client error - cause description: 'Middleware of type 'GHMiddleware' threw an error.', underlying error: JWTKit error: signing algorithm error: bioConversionFailure, operationID: repos/list-pull-requests-associated-with-commit, operationInput: Input(path: GitHubAPI.Operations.repos_list_pull_requests_associated_with_commit.Input.Path(owner: "vapor", repo: "design", commit_sha: "76b5bae373c5014c844c35d616979bc1fac55516"), query: GitHubAPI.Operations.repos_list_pull_requests_associated_with_commit.Input.Query(per_page: nil, page: nil), headers: GitHubAPI.Operations.repos_list_pull_requests_associated_with_commit.Input.Headers(accept: [OpenAPIRuntime.AcceptHeaderContentType<GitHubAPI.Operations.repos_list_pull_requests_associated_with_commit.AcceptableContentType>(contentType: GitHubAPI.Operations.repos_list_pull_requests_associated_with_commit.AcceptableContentType.json, quality: OpenAPIRuntime.QualityValue(thousands: 1000))])), request: GET /repos/vapor/design/commits/76b5bae373c5014c844c35d616979bc1fac55516/pulls [accept: application/json], requestBody: <nil>, baseURL: https://api.github.com/, response: <nil>, responseBody: <nil>"])

**Comment by 0xTim** [comment]
I don't see a decoding error in the error message? The signing error would suggest the keys aren't being passed correctly

**Comment by MahdiBM** [comment]
So 2 things, 1- I hadn't touched anything when this happened and 2, I think the JWT 5 update made the error be like this instead:

multipleErrors(["Client error - cause description: 'Middleware of type 'GHMiddleware' threw an error.', underlying error: httpRequestFailed(response: unauthorized(GitHubAPI.Components.Responses.requires_authentication(body: GitHubAPI.Components.Responses.requires_authentication.Body.json(GitHubAPI.Components.Schemas.basic_error(message: Optional("\'Expiration time\' claim (\'exp\') must be a numeric value representing the future time at which the assertion expires"), documentation_url: Optional("[https://docs.github.com/rest/"](https://docs.github.com/rest/%22)), url: nil, status: Optional("401"))))), file: /__w/penny-bot/penny-bot/penny-bot/Lambdas/GHHooks/Authenticator.swift, line: 62), operationID: repos/list-pull-requests-associated-with-commit, operationInput: Input(path: GitHubAPI.Operations.repos_list_pull_requests_associated_with_commit.Input.Path(owner: "vapor", repo: "penny-bot", commit_sha: "6000ed123d09813d095b4307290fa6257da83f0a"), query: GitHubAPI.Operations.repos_list_pull_requests_associated_with_commit.Input.Query(per_page: nil, page: nil), headers: GitHubAPI.Operations.repos_list_pull_requests_associated_with_commit.Input.Headers(accept: [OpenAPIRuntime.AcceptHeaderContentType<GitHubAPI.Operations.repos_list_pull_requests_associated_with_commit.AcceptableContentType>(contentType: GitHubAPI.Operations.repos_list_pull_requests_associated_with_commit.AcceptableContentType.json, quality: OpenAPIRuntime.QualityValue(thousands: 1000))])), request: GET /repos/vapor/penny-bot/commits/6000ed123d09813d095b4307290fa6257da83f0a/pulls [accept: application/json], requestBody: <nil>, baseURL: https://api.github.com/, response: <nil>, responseBody: <nil>"])

which indicates that the token has been created and sent to GitHub but GitHub didn't like the `exp` or something else in it.

**Comment by ptoffy** [comment]
@MahdiBM this is working for me
```swift
let encoder = JSONEncoder()
encoder.dateEncodingStrategy = .integerSecondsSince1970
let decoder = JSONDecoder()
decoder.dateDecodingStrategy = .integerSecondsSince1970

let date = Date.now.addingTimeInterval(5 * 60)

let payload = TestPayload(
    sub: "vapor",
    name: "Foo",
    admin: false,
    exp: .init(value: date)
)
let keyCollection = await JWTKeyCollection().addUnsecuredNone(
    parser: DefaultJWTParser(jsonDecoder: decoder),
    serializer: DefaultJWTSerializer(jsonEncoder: encoder)
)
let token = try await keyCollection.sign(payload)
#expect(
    (token.split(separator: ".").dropFirst(1).first.map {
        String(decoding: Data($0.utf8).base64URLDecodedBytes(), as: UTF8.self)
    } ?? "").contains(#""exp":\#(Int(date.timeIntervalSince1970))"#))
await #expect(throws: Never.self) {
    try await keyCollection.verify(token, as: TestPayload.self)
}
```
Note that if you actually compare the two payloads it will fail as the parsed token has just an integer timeInterval as exp while the types payload actually has the precise Double timeInterval. But that's really just a testing problem and shouldn't matter here

**Comment by MahdiBM** [comment]
I cannot seem to reproduce this ... closing for now although it definitely did happen as y'all also probably noticed when Penny was reporting errors.

**Comment by MahdiBM** [comment]
Leaving this right here, might come handy in the future if I want to test again:

```swift
@testable import JWTKit

    @Test(arguments: 1...10)
    func createJWTToken(run: Int) async throws {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .integerSecondsSince1970
        encoder.outputFormatting = .sortedKeys
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .integerSecondsSince1970

        let date = Date()
        let payload1 = TokenPayload1(date: date)
        let payload2 = TokenPayload2(date: date)
        let keyCollection = await JWTKeyCollection().addUnsecuredNone(
            parser: DefaultJWTParser(jsonDecoder: decoder),
            serializer: DefaultJWTSerializer(jsonEncoder: encoder)
        )
        let token1 = try await keyCollection.sign(payload1)
        let token2 = try await keyCollection.sign(payload2)
        let token1Split = token1.split(separator: ".")
        let token2Split = token2.split(separator: ".")
        for (part1, part2) in zip(token1Split, token2Split) {
            let part1Decoded = String(data: Data(part1.data(using: .utf8)!.base64URLDecodedBytes()), encoding: .utf8)!
            let part2Decoded = String(data: Data(part2.data(using: .utf8)!.base64URLDecodedBytes()), encoding: .utf8)!
            #expect(token1 == token2)
        }
    }

private struct TokenPayload1: JWTPayload, Equatable {
    /// When the token was issued.
    let issuedAt: Int
    /// When the token will expire.
    let expiresAt: Int
    /// Penny's GitHub app-id.
    let issuer: String
    /// The algorithm. GitHub says `RS256`.
    let algorithm: String

    enum CodingKeys: String, CodingKey {
        case issuedAt = "iat"
        case expiresAt = "exp"
        case issuer = "iss"
        case algorithm = "alg"
    }

    init(date: Date) {
        /// 60s in the past, per GitHub docs.
        self.issuedAt = Int(date.addingTimeInterval(-60).timeIntervalSince1970.rounded(.towardZero))
        /// 5 mins into the future. GitHub docs says no more than 10 mins.
        self.expiresAt = Int(date.addingTimeInterval(5 * 60).timeIntervalSince1970.rounded(.towardZero))
        /// The app-id, per GitHub docs.
        self.issuer = "\(360798)"
        /// `RS256`, per GitHub docs.
        self.algorithm = "RS256"
    }

    // Run any additional verification logic beyond
    // signature verification here.
    // Since we have an ExpirationClaim, we will
    // call its verify method.
    func verify(using algorithm: some JWTAlgorithm) async throws {

    }
}

private struct TokenPayload2: JWTPayload, Equatable {
    /// When the token was issued.
    let issuedAt: IssuedAtClaim
    /// When the token will expire.
    let expiresAt: ExpirationClaim
    /// Penny's GitHub app-id.
    let issuer: String
    /// The algorithm. GitHub says `RS256`.
    let algorithm: String

    enum CodingKeys: String, CodingKey {
        case issuedAt = "iat"
        case expiresAt = "exp"
        case issuer = "iss"
        case algorithm = "alg"
    }

    init(date: Date) {
        /// 60s in the past, per GitHub docs.
        self.issuedAt = .init(value: date.addingTimeInterval(-60))
        /// 5 mins into the future. GitHub docs says no more than 10 mins.
        self.expiresAt = .init(value: date.addingTimeInterval(5 * 60))
        /// The app-id, per GitHub docs.
        self.issuer = "\(360798)"
        /// `RS256`, per GitHub docs.
        self.algorithm = "RS256"
    }

    // Run any additional verification logic beyond
    // signature verification here.
    // Since we have an ExpirationClaim, we will
    // call its verify method.
    func verify(using algorithm: some JWTAlgorithm) async throws {

    }
}
```
