### ISSUE TITLE
Add installation steps?

### ISSUE THREAD

**Issue by MahdiBM** [vapor/jwt-kit#209]
### Please summarize your feature request

Add installation steps containing the new Swift 6 commands

### Describe the functionality you're seeking in more detail

Like this, but I'd put the command line stuff at the top: https://github.com/hummingbird-project/hummingbird?tab=readme-ov-file#installation

### Have you considered any alternatives?

Not having the installation steps, like what currently is the case.

**Comment by ptoffy** [comment]
@MahdiBM want to do a PR? 😁
