### ISSUE TITLE
Using for Sign in with Apple verify token

### ISSUE THREAD

**Issue by ashish-naik** [vapor/jwt-kit#4]
Can this package be used token verification in Sign in with Apple?

how do I use it exactly? How do i get the secret and compare with "sub"?

Thanks
Ashish

**Comment by landsv** [comment]
Hi, I have not tried to do that, but I believe the flow should be next:
1. Receive IdentityToken in your iOS app when user logs in using Apple Sing in button
2. Send that IdentityToken and user id to server
3. Server gets JWK(Apple public key) and using it verifies received IdentityToken from previous step, you can do that with JWTSigner from JWT package
4. If token is valid that means it was generated by Apple so the user is authentic
5. Generate JWT for that user/save to DB and so on
This https://sarunw.com/posts/sign-in-with-apple-3/ might be helpful

**Comment by grosch** [comment]
@ashish-naik please use https://github.com/vapor-community/JWT3PA for this.

**Comment by tanner0101** [comment]
Check out this file which adds helper methods for using Apple JWTs: https://github.com/vapor/jwt/blob/master/Sources/JWT/JWT%2BApple.swift

Note that is part of the JWT package which integrates JWTKit with Vapor. JWTKit just covers basic JWT handling.
