### ISSUE TITLE
Missing typ field in the header

### ISSUE THREAD

**Issue by KleMiX** [vapor/jwt-kit#5]
There must be a `typ: "JWT"` field in the header. At least MapKit is giving a warning about it missing.
And there is no way to modify header, since it is created in `JWTSerializer` which is internal.

**Comment by tanner0101** [comment]
From what I can tell in https://tools.ietf.org/html/rfc7519 it seems like this should just be set to `"JWT"`. 

>    The following example JOSE Header declares that the encoded object is
>   a JWT, and the JWT is a JWS that is MACed using the HMAC SHA-256
>   algorithm:
>
>     {"typ":"JWT",
>      "alg":"HS256"}

If that seems correct, we could add it here: https://github.com/vapor/jwt-kit/blob/master/Sources/JWTKit/JWTSerializer.swift#L17

**Comment by Maxim-Inv** [comment]
@tanner0101 could you review my PR #27? I'll be very appreciated.
