### ISSUE TITLE
Export keys as PEM string

### ISSUE THREAD

**Issue by FabioTacke** [vapor/jwt-kit#53]
jwt-kit allows importing externally generated ECDSA key pairs via PEM string representation. Although jwt-kit offers the ability to generate ECDSA private keys it lacks support of exporting them and their corresponding public keys. In order to persist a key pair it still has to be generated externally.
It would be nice to be able to export private and public ECDSA keys as PEM strings.

**Comment by ptoffy** [comment]
Added in #120!
