### ISSUE TITLE
How to verify claims using dynamic data?

### ISSUE THREAD

**Issue by natep** [vapor/jwt-kit#54]
Hey Folks,

Just trying out this project for the first time, and have quickly run into an issue with verifying claims.

According to the README:

> All claims should be verified in the JWTPayload.verify method. If the claim has a special verify method, you can use that. Otherwise, access the value of the claim using value and check that it is valid.

And that makes sense. But how do I verify a claim that requires dynamic data? For instance, if I want to ensure that the `subject` matches a particular string value - how do I make that string value available inside `JWTPayload.verify()`? (Without making it a global variable, which I'd rather avoid.)

I could add an additional verify method to my payload (like `verifyExtended()`) that takes the extra parameter I need. But then I need to ensure that extra verification method is called every time, which seems error-prone.

Let me know if I am missing something obvious here (very possible).

**Comment by 0xTim** [comment]
When you conform you type to `JWTPayload()` you can add the types you want on your payload, like `subject` and then check them in the `verify` function. See [the tests](https://github.com/vapor/jwt-kit/blob/main/Tests/JWTKitTests/JWTKitTests.swift#L21) as an example.

PS sorry it's taken so long to provide an answer!

**Comment by tomlokhorst** [comment]
But how do you actually verify claims  using dynamic data?

To stick with the example from the tests, how do you verify that the subject is "vapor" without hardcoding that string inside the verify method?

**Comment by vzsg** [comment]
There may be a slight misunderstanding, at least I read it differently :)

Consider this test: https://github.com/vapor/jwt-kit/blob/main/Tests/JWTKitTests/JWTKitTests.swift#L93, what could one do to replace "foo" with something dynamic?

I only see two options, which were already touched:

1. a static/global place to get the value from — including actual global variables, the environment, a service locator or a conveniently placed Application instance;
2. or not playing this game at all in the verify method, but doing additional checks at the call site where the Payload will be consumed. The aforementioned verifyExtended method is the same, but an even more manual approach is visible in the tests where the audience claim is [asserted from the outside](https://github.com/vapor/jwt-kit/blob/main/Tests/JWTKitTests/JWTKitTests.swift#L594).

And I don't think there's another way. 🤔

**Comment by 0xTim** [comment]
Ahhh right sorry I misunderstood. Yeah there's no way to do what you want at the moment and I'm struggling to think of a nice way to implement it. Your best bet is probably number 2 from @vzsg and do it out of band
