### ISSUE TITLE
Segmentation fault when creating EC private key from PEM string using Swift 5.4

### ISSUE THREAD

**Issue by FabioTacke** [vapor/jwt-kit#56]
### Describe the bug

When using Swift 5.4 creating an EC private key from a PEM string causes a segmentation fault. This does only happen when executing the program from the command line and not when using Xcode.

### To Reproduce

1. Setup empty swift package project (executable) with jwt-kit as dependency.
2. In `main.swift` add statement `try ECDSAKey.private(pem: pemString)` with `pemString` containing a valid PEM string.
3. Execute `swift run` from the command line.

### Expected behavior

The statement should return an ECDSAKey instance.

### Environment

Swift 5.4 installed via Xcode 12.5
macos 11.3
jwt-kit 4.2.2

**Comment by FabioTacke** [comment]
Seems to be a swift bug: https://bugs.swift.org/browse/SR-14543

**Comment by 0xTim** [comment]
Yes this is a Swift bug unfortunately. It might work if you pass `--sanitize=address` through to the `swift run` call

**Comment by FabioTacke** [comment]
I just gave it a shot and using the sanitizer the program runs perfectly! Thank you so much for sharing this workaround, @0xTim!

**Comment by 0xTim** [comment]
Closing as this is a Swift bug
