### ISSUE TITLE
Q: is JWTSigners() thread safe?

### ISSUE THREAD

**Issue by crontab** [vapor/jwt-kit#69]
I'm building a server app based on SwiftNIO (i.e. not Vapor) and I was wondering if I should create one instance of JWTSigners per app, per EventLoop or per each request handler?

This is something worth mentioning in the documentation btw - unless I missed it somehow, of course.

Edit: do I understand it correctly that if I create a `JWTSigner` instead of `JWTSigners` at program startup then any calls to `sign()` or `verify()` can be considered thread-safe?

**Comment by ptoffy** [comment]
Done in #116
