### ISSUE TITLE
Problems on M1

### ISSUE THREAD

**Issue by mamouneyya** [vapor/jwt-kit#70]
### Describe the bug

I am not honestly sure what's the root cause exactly. However, I have a super simple app that I use to generate JWT tokens in order to consume Apple's StoreKit v2 REST APIs. The app relies on this package, which is consumed via SwiftPM. When I build the app using my M1 MacBook Pro, the generated token never works. It does if I build with Rosetta enabled though, which makes me think it's an issue.

### To Reproduce

1. Build the package using a M1 Mac machine (with Rosetta disabled). 
2. Try to generate a JWT token. 

### Expected behavior

The token should be valid. Currently it is not.

### Environment

* Vapor Framework version: 4.4.0
* Vapor Toolbox version: 4.4.0
* OS version: 12.3.1 (21E258)

### Additional context
I can attach the project if that helps.

**Comment by mamouneyya** [comment]
Just figured I can attach my implementation anyway. It's super straightforward. Here is it with the sensitive information redacted:

```
// Docs:
// https://developer.apple.com/documentation/appstoreserverapi/generating_tokens_for_api_requests

enum TokenGenerator {
    
    enum Defaults {
        static let keyID = "REDACTED"
        static let issuer = "REDACTED"
        static let bundleID = "REDACTED"
        static let privateKey = """
        -----BEGIN PRIVATE KEY-----
        REDACTED
        -----END PRIVATE KEY-----
        """
        
        static let issuedAt = Date()
        static let expiration = Date().advanced(by: 60 * 60)
    }
    
    static func generate(
        keyID: String = Defaults.keyID,
        issuer: String = Defaults.issuer,
        issuedAt: Date = Defaults.issuedAt,
        expiration: Date = Defaults.expiration,
        bundleID: String = Defaults.bundleID,
        privateKey: String = Defaults.privateKey
    ) throws -> String {
        let payload = TokenPayload(
            issuer: .init(value: issuer),
            issuedAt: .init(value: issuedAt),
            expiration: .init(value: expiration),
            audience: "appstoreconnect-v1",
            bundleID: bundleID
        )
        
        let signers = JWTSigners()
        try signers.use(.es256(key: .private(pem: privateKey)))
        return try signers.sign(payload, kid: .init(string: keyID))
    }
        
}

private struct TokenPayload: JWTPayload, Equatable {
    
    enum CodingKeys: String, CodingKey {
        case issuer = "iss"
        case issuedAt = "iat"
        case expiration = "exp"
        case audience = "aud"
        case bundleID = "bid"
    }
    
    let issuer: IssuerClaim
    let issuedAt: IssuedAtClaim
    let expiration: ExpirationClaim
    let audience: AudienceClaim
    let bundleID: String
    
    func verify(using signer: JWTSigner) throws {
        try expiration.verifyNotExpired()
        try audience.verifyIntendedAudience(includes: "appstoreconnect-v1")
    }
    
}
```

**Comment by 0xTim** [comment]
@mamouneyya can you update to latest JWTKit (https://github.com/vapor/jwt-kit/releases/tag/4.5.0) - I've just updated BoringSSL which _might_ help

**Comment by mamouneyya** [comment]
Just had a chance to test again with 4.6.0. Looks like my app works properly now even when not using Rosetta. Will close the ticket. Thank you very much!
