### ISSUE TITLE
https://jwt.io/  have `secret base64 encoded` how test

### ISSUE THREAD

**Issue by VineFiner** [vapor/jwt-kit#89]
I selected `secret base64 encoded`, how should I set it?

**Comment by VineFiner** [comment]
```
HMACSHA256(
  base64UrlEncode(header) + "." +
  base64UrlEncode(payload),
  
your-256-bit-secret

) 口 secret base64 encoded
```
- if selected `secret base64 encoded` error

**Comment by 0xTim** [comment]
I'm guessing the secret isn't encoded correctly. I'm going to close this issue as it's not Vapor issue and Vapor's Discord is a much better place for these questions - please ask over there. Thanks!
